exports.el = {
    inputName: 'input[type="text"]',
    inputEmail: 'input[data-qa="signup-email"]',
    signupButton: 'button[data-qa="signup-button"]',
    signupFormBeVisible: 'div[class="login-form"]',
    title: 'input[value=',
    pass: '#password',
    day: '#days',
    month: '#months',
    year: '#years',
    newsletter: '#newsletter',
    optin: '#optin',
    firstName: '#first_name',
    lastName: '#last_name',
    company: '#company',
    adress1: '#address1',
    adress2: '#address2',
    country: '#country',
    state: '#state',
    city: '#city',
    zipcode: '#zipcode',
    number: '#mobile_number',
    submitButton: 'button[data-qa="create-account"]',
    successfulMessage: 'h2[class="title text-center"] b'
}