
exports.el = {
    inputName: 'input[data-qa="signup-name"]',
    inputEmail: 'input[data-qa="signup-email"]',
    signupButton: 'button[data-qa="signup-button"]',
    valueName: '#name',
    valueEmail: '#email',
    title: 'input[value=',
    inputPassword: '#password',
    selectDay: '#days',
    selectMonth: '#months',
    selectYear: '#years',
    checkNewsletter: '#newsletter',
    checkOptin: '#optin',
    inputFirstName: '#first_name',
    inputLastName: '#last_name',
    inputCompany: '#company',
    inputAddress1: '#address1',
    inputAddress2: '#address2',
    selectCountry: '#country',
    inputState: '#state',
    inputCity: '#city',
    inputZipcode: '#zipcode',
    inputMobilenumber: '#mobile_number',
    submitButton: 'button[data-qa="create-account"]',
    successfulMsg: 'h2[data-qa="account-created"] b',

}